# Project information
site_name: Getting Started with IKS
site_url: https://greyhoundforty.github.io/ibmcloud-kubernetes-getting-started 
site_author: Ryan Tiffany

# # Repository
# repo_name: workshop-setup
# repo_url: https://github.com/remkohdev/workshop-setup
# edit_uri: edit/master/docs

# Navigation
nav:
  - Welcome:
    - About this Guide: README.md
  - Guides:
    - 1. Pre-work: pre-work/README.md
    - 2. Kubernetes Overview: 01-kubernetes/README.md
    - 3. Deploy Kubernetes on IBM Cloud: 02-deploy-iks/README.md
    - 4. Deploy and configure IKS Add-ons: 03-add-ons/README.md
  - References:
    - Additional Resources: resources/RESOURCES.md
    - Contributors: resources/CONTRIBUTORS.md
    - MkDocs Cheatsheet: resources/MKDOCS.md

## DO NOT CHANGE BELOW THIS LINE

# Copyright
copyright: Copyright &copy; 2022 Ryan Tiffany

# Theme
theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    logo: material/library
  features:
    - navigation.tabs
    #- navigation.instant
  palette:
    scheme: default
    primary: blue
    accent: blue

# Plugins
plugins:
  - search

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/greyhoundforty
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ryantiffany
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ibm/
    - icon: fontawesome/brands/dev
      link: https://dev.to/greyhoundforty

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde